# Use the official Node.js image
FROM node:22.14.0

# Set the working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package.json package-lock.json ./
RUN npm install --verbose

# Copy the rest of the frontend code
COPY . .

# Expose frontend port
EXPOSE 3000

# Start the frontend
CMD ["npm", "run", "dev"]
